version = 0.1

[default.deploy.parameters]
stack_name = "donut-gallery-stack"
resolve_s3 = true
s3_prefix = "donut-gallery-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
